// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNOJ2TF6_GF0SSYrDyxyW4o4fDEplOf_o',
    appId: '1:602720868878:web:30ab76c8fdc77025acba5f',
    messagingSenderId: '602720868878',
    projectId: 'bikeshop-d08d1',
    authDomain: 'bikeshop-d08d1.firebaseapp.com',
    storageBucket: 'bikeshop-d08d1.appspot.com',
    measurementId: 'G-7RCR9TRPQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA17k4-NN1utoxPVpUjRhybOTosHpCsMlw',
    appId: '1:602720868878:android:ef9dae42425e4506acba5f',
    messagingSenderId: '602720868878',
    projectId: 'bikeshop-d08d1',
    storageBucket: 'bikeshop-d08d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEqwQsvzXJ_sjbecPcIhJJLvzn3Eyos94',
    appId: '1:602720868878:ios:5a5853ad31345c9eacba5f',
    messagingSenderId: '602720868878',
    projectId: 'bikeshop-d08d1',
    storageBucket: 'bikeshop-d08d1.appspot.com',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEqwQsvzXJ_sjbecPcIhJJLvzn3Eyos94',
    appId: '1:602720868878:ios:5cdea8541a30bb02acba5f',
    messagingSenderId: '602720868878',
    projectId: 'bikeshop-d08d1',
    storageBucket: 'bikeshop-d08d1.appspot.com',
    iosBundleId: 'com.example.quiz.RunnerTests',
  );
}
